import Head from "next/head";
import React from "react";
import { useQuery, gql } from "@apollo/client";
import { Heading, Grid, GridItem,Text} from "@chakra-ui/react";
import ConfessionCard from "../../components/ConfessionCard";
import ConfessionCardSkeleton from "../../components/skeleton/ConfessionCardSkeleton";

import { useAccount } from "wagmi";

const GET_CONFESSIONS = gql`
  query confessions(
    $first: Int
    $skip: Int
    $orderBy: String
    $orderDirection: String
    $where: Confession_filter
  ) {
    confessions(
      first: $first
      skip: $skip
      orderBy: $orderBy
      orderDirection: $orderDirection
      where: $where
    ) {
      id
      hash
      message
      category
      timestamp
      author
    }
  }
`;

const myConfessions = () => {
 
 const account = useAccount();

  const { loading, error, data } = useQuery(GET_CONFESSIONS, {
    variables: {
      first: 10,
      skip: 0,
      orderBy: "timestamp",
      orderDirection: "desc",
     
        where: {author :  account.address },
      
    },
  });

  
   
 
  return (

    <div>
      <Head>
        <title>My Confession</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
     

        
        <Grid
          mt="10"
          templateColumns={{
            base: "repeat(1, 1fr)",
            md: "repeat(2, 1fr)",
          }}
          gap={6} 
          justifyContent={"center"}
        >
          {loading
            ? new Array(4).fill(0).map((_, index) => (
                <GridItem key={index}>
                  <ConfessionCardSkeleton />
                </GridItem>
              ))
            : data?.confessions?.map((confession, index) => (
                <GridItem colSpan={1} key={confession.id}>
                  <ConfessionCard confession={confession} index={index} />
                </GridItem>
              ))}

             
         
          
        </Grid>
      </main>
    </div>
  );
};




export default myConfessions;